#!/usr/bin/env bash

##
# Color  Variables
##
green='\e[32m'
blue='\e[34m'
red='\e[31m'
clear='\e[0m'

##
# Color Functions
##

ColorGreen() {
    echo -ne "$green$1$clear"
}
ColorBlue() {
    echo -ne "$blue$1$clear"
}

check_cmd() {
    if [[ ! $(command -v "$1") ]]; then
        app=$1
        echo "It seems like you don't have ${app}."
        echo "Please install ${app}."
        exit 1
    fi
}

# cleanup() {
#     rm -f "/tmp/*.json"
# }

# trap cleanup EXIT
# trap cleanup ERR

# cleanup
_clean_tmp() {
    if [[ -f "/tmp/radio_searches.json" ]]; then
        rm /tmp/radio_searches.json
    fi
}

_cleanup_tmp() {
    FILE=$1
    if [[ -f "$FILE" ]]; then
        rm "$FILE"
    fi
}

# shellcheck disable=SC2120
_fav_list() {
    arr=("$FAVORITE_PATH"/*.json)
    list=()
    for f in "${arr[@]}"; do
        if [ $# -ge 1 ] && [ -n "$1" ]; then
            # if any argument is given then show all
            name=$(basename "$f")
            list+=("${name%.*}")
        else
            if [ -s "$f" ]; then
                # otherwise show files with content
                name=$(basename "$f")
                list+=("${name%.*}")
            fi
        fi

    done
    echo "${list[@]}"
}

_station_list() {
    jq -r '.[] | .name' <"$FAVORITE_PATH/$1.json"
}

_play() {
    echo
    echo "Press q to quit."
    echo
    mpv "$1"
}

_show_favlist() {
    LISTS=$(_fav_list)
    # lists=""
    # echo "$lists"
    if [ -z "$LISTS" ]; then
        echo "lists is empty"
        echo "try $SCRIPT_NAME search"
    fi

    PS3="Enter a number: "
    select LIST in $LISTS; do
        # echo "Selected list: $LIST"
        break
    done
    echo "$LIST"
}
