#!/usr/bin/env bash

# RADIO_BROWSER="http://91.132.145.114/json/stations/search"

_search_play() {
    # echo "$1" # this is a list number in "$SEARCH_RESULTS"
    ANS=$1
    URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"$SEARCH_RESULTS")
    mpv "$URL_RESOLVED"
}

_save_station() {
    FILE1="/tmp/radio_favorite.json"
    FILE2="/tmp/radio_favorite2.json"
    _cleanup_tmp $FILE1
    _cleanup_tmp $FILE2
    TEMP_FILE=$(mktemp "$FILE1")
    TEMP_FILE2=$(mktemp "$FILE2")
    # echo "$1" # list number
    ANS=$1
    echo "Select the list to save to: "
    # echo saving
    LIST_NAME=$(_show_favlist)
    echo "$LIST_NAME"
    FAVORITE_FULL="${FAVORITE_PATH}/${LIST_NAME}.json"
    # echo "$FAVORITE_FULL"
    # get item from "$SEARCH_RESULTS" using $ANS

    jq ".[$ANS-1]" <"$SEARCH_RESULTS" >"$TEMP_FILE"
    # add the item to the fav list
    # jq '. += [input]' "$FAVORITE_FULL" "$TEMP_FILE"
    jq '. += [input]' "$FAVORITE_FULL" "$TEMP_FILE" >"$TEMP_FILE2" && mv "$TEMP_FILE2" "$FAVORITE_FULL"
    # which list?
    echo "Successfull save it to your $LIST_NAME list."
    # STATIONS=$(_station_list "$LIST")
    # echo "$STATIONS" | nl
    # save it to the list
    search_submenu
}

_save_play() {
    echo "Save & Play"
}

search_submenu() {
    echo -ne "
$SCRIPT_NAME SELECT:
$(ColorGreen '1)') Play
$(ColorGreen '2)') Save
$(ColorGreen '3)') Go back to the Main menu
$(ColorGreen '4)') Go back to the Search menu
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an option:') "
    read -r a
    case $a in
    1)
        echo "Playing $ANS"
        _search_play "$ANS"
        menu
        ;;
    2)
        echo "Saving $ANS"
        _save_station "$ANS"
        menu
        ;;
    3)
        echo "Go back to the Main menu"
        menu
        ;;
    4)
        echo "Go back to the Search menu"
        search_menu
        ;;
    0) exit 0 ;;
    *)
        echo -e $red"Wrong option."$clear
        # WrongCommand
        exit 1
        ;;
    esac
}

search_by() {
    KEY=$1
    SEARCH_RESULTS=$(mktemp /tmp/radio_searches.json)
    read -rp "Type a $KEY to search. " RES
    OPTS=()
    for TAG in "${RES[@]}"; do
        OPTS+=(-d "$KEY=$TAG")
    done

    curl -X POST "${OPTS[@]}" "$SEARCH_URL" -o "$SEARCH_RESULTS" >&/dev/null

    jq -r '.[].name' <"$SEARCH_RESULTS" | nl
    read -rp "Select a number. " ANS
    # echo "$ANS"

    # URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"$SEARCH_RESULTS")
    search_submenu "$ANS"
    # rm "$SEARCH_RESULTS"
}
