#!/usr/bin/env bash

set -eu

# shellcheck disable=SC2034
VERSION="0.3.8"
SCRIPT_DOT_DIR="$HOME/.config/tera"
# CACHE_DIR="$HOME/.cache"
FAVORITE_PATH="$SCRIPT_DOT_DIR/favorite"
TMP_PATH="$HOME/.cache/tera"
FAVORITE_FILE="sample.json"
FAVORITE_FULL="${FAVORITE_PATH}/${FAVORITE_FILE}"
SCRIPT_NAME=$(basename "$0")
APP_NAME="TERA"
RADIO_BROWSER="https://de1.api.radio-browser.info/json/stations/bytag/"
SEARCH_URL="http://all.api.radio-browser.info/json/stations/search"

# rm /tmp/*.json

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

# $0 may have ./ in ./script_name
# then use pwd

if [[ -z $(which "${SCRIPT_NAME}") || $0 = "./${SCRIPT_NAME}" ]]; then
    # echo "in 1"
    script_path=$(myrealpath "$0")
    # script_path=${script_path%/*}
else
    # echo "in 2"
    script_path=$(myrealpath "$(which "${SCRIPT_NAME}")")
fi

script_dir="${script_path%/*}"
# shellcheck disable=SC1091
{
    source "${script_dir}/lib"
    source "${script_dir}/search"
    source "${script_dir}/list"
    source "${script_dir}/lucky"
    source "${script_dir}/play"
    source "${script_dir}/delete_station"
    source "${script_dir}/gistlib"
}

check_cmd mpv
check_cmd jq
check_cmd fzf

# check ~/.tera/favorite
if [ ! -d "$FAVORITE_PATH" ]; then
    mkdir -p "$FAVORITE_PATH"
fi
if [ ! -d "$TMP_PATH" ]; then
    mkdir -p "$TMP_PATH"
fi
if [ ! -f "$FAVORITE_FULL" ]; then
    touch "$FAVORITE_FULL"
    cp "${script_dir}/sample.json" "$FAVORITE_FULL"
fi

menu() {
    echo -ne "
$APP_NAME MAIN MENU
$(greenprint '1)') Play from my list
$(greenprint '2)') Search radio stations
$(greenprint '3)') List (Create/Read/Update/Delete)
$(greenprint '4)') Delete a radio station 
$(greenprint '5)') I feel lucky
$(greenprint '6)') Gist
$(greenprint '0)') Exit
$(blueprint 'Choose an option:') "
    read -r ans
    case $ans in
    1)
        fn_play
        menu
        ;;
    2)
        search_menu
        menu
        ;;
    3)
        list_menu
        menu
        ;;
    4)
        fn_delete
        menu
        ;;
    5)
        fn_lucky
        menu
        ;;
    6)
        gist_menu
        menu
        ;;
    0)
        echo "Bye bye."
        exit 0
        ;;
    *)
        redprint 'Wrong option.'
        exit 1
        ;;
    esac
}

usage() {
    cat <<EOF
    Name: $APP_NAME

    Usage:
    $SCRIPT_NAME

EOF
}

while (($# > 0)); do
    case $1 in
    -V | --version)
        echo $VERSION
        exit
        ;;
    -h | --help | *)
        usage
        exit
        ;;
    esac
done

menu
