#!/bin/bash
# Test the quit functionality fixes

echo "🔧 Building with quit fixes..."
make clean
make build

if [ ! -f "./tera" ]; then
    echo "❌ Build failed!"
    exit 1
fi

echo "✅ Build successful!"
echo ""
echo "📋 Quit Fixes:"
echo "  1. ✅ 'q' key works from main menu (any menu position)"
echo "  2. ✅ Search play → q → Player stops AND save prompt shows"
echo ""
echo "🧪 Manual Tests:"
echo ""
echo "Test 1 - Main Menu Quit:"
echo "  • Run: ./tera"
echo "  • Navigate to any menu item (not just Exit)"
echo "  • Press 'q'"
echo "  • Expected: Application quits immediately"
echo "  • Verify: No error messages"
echo ""
echo "Test 2 - Search Play Quit (Main Fix):"
echo "  • Run: ./tera"
echo "  • Press 2 (Search)"
echo "  • Search for a station"
echo "  • Select and play a station"
echo "  • Wait for audio to start"
echo "  • Press 'q'"
echo "  • Expected: Audio stops IMMEDIATELY"
echo "  • Expected: Save prompt appears"
echo "  • Verify: ps aux | grep mpv (should be empty)"
echo ""
echo "Test 3 - Verify No Zombie Process:"
echo "  • After Test 2"
echo "  • Run: ps aux | grep mpv"
echo "  • Expected: No MPV processes running"
echo "  • Expected: Only the grep command shows up"
echo ""
echo "Test 4 - Play from Favorites Quit:"
echo "  • Run: ./tera"
echo "  • Press 1 (Play from Favorites)"
echo "  • Select a list and station"
echo "  • Press 'q'"
echo "  • Expected: Audio stops"
echo "  • Expected: Returns to station list"
echo "  • Verify: No zombie process"
echo ""
echo "Test 5 - Complete Flow:"
echo "  • Search → Play → Press q"
echo "  • Choose 'y' to save"
echo "  • Return to main menu"
echo "  • Press 'q' to quit"
echo "  • Expected: Clean exit, no audio playing"
echo ""
echo "🚀 Ready to test! Run: ./tera"
echo ""
echo "⚠️  IMPORTANT CHECKS:"
echo "  1. Audio stops when pressing q (not after quit)"
echo "  2. Save prompt appears after audio stops"
echo "  3. No orphan MPV processes"
echo "  4. q works from any position in main menu"
